In [3]:
import pandas as pd
import os
import shutil
from tqdm import tqdm
import torch
import torch.nn as nn
import numpy as np
import torchvision
from torchvision import transforms,datasets
from torch.utils.data import Dataset,DataLoader,random_split

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
DEVICE

device(type='cuda', index=0)

## 数据集：多种肺炎X光图像

### 数据集

In [4]:
data_dir = "../data/COVID_Dataset"
TRAIN = 'train'
TEST = 'test'
VAL = 'val'

def apply_transform(mode=None):
    size = (299,299)
    crop = 299
    if mode == 'train':
        transform = transforms.Compose([transforms.Resize(size),
                               transforms.RandomHorizontalFlip(),
                               transforms.RandomRotation((-20,+20)),
                               transforms.CenterCrop(crop),
                               transforms.ToTensor(),
                               transforms.Normalize([0.485, 0.456, 0.406],
                                           [0.229, 0.224, 0.225])
                              ])

    elif mode == 'test' or mode == 'val':
        transform = transforms.Compose([transforms.Resize(size),
                               transforms.CenterCrop(crop),
                               transforms.ToTensor(),
                               transforms.Normalize([0.485, 0.456, 0.406],
                                           [0.229, 0.224, 0.225])
                              ])

    return transform

trainset = datasets.ImageFolder(os.path.join(data_dir, TRAIN),
                                transform = apply_transform(TRAIN))

trainset,valset = random_split(trainset,[len(trainset)-int(len(trainset)*0.1),int(len(trainset)*0.1)])

testset = datasets.ImageFolder(os.path.join(data_dir, TEST),
                               transform = apply_transform(TEST))

train_loader = DataLoader(trainset,
                          batch_size=50,
                          shuffle=True)

val_loader = DataLoader(valset,
                        batch_size=10)

test_loader = DataLoader(testset,
                         batch_size=1)

len(train_loader),len(test_loader),len(val_loader)




(439, 2706, 244)

### 模型

In [5]:
def get_deepLavV3(out_ch):
    model = torchvision.models.inception_v3(pretrained=True)
    # 冻结参数
    for param in model.parameters():
        param.requires_grad = False
    in_features = model.fc.in_features
    classifier = nn.Sequential(
        nn.Linear(in_features, 4096),
        nn.ReLU(inplace=True),
        nn.Dropout(0.5),
        nn.Linear(4096, 4096),
        nn.ReLU(inplace=True),
        nn.Dropout(0.5),
        nn.Linear(4096, out_ch),
        nn.LogSoftmax(dim=1)
    )
    model.fc = classifier
    return model

# model = get_deepLavV3(2)
# print(model)
# x = torch.tensor(np.random.random((2,3,299,299))).float()
# y,_ = model(x)
# y.shape,_.shape


### 评价指标

In [6]:
def accuracy(preds, labels):
    preds = torch.exp(preds)
    top_p,top_class = preds.topk(1, dim=1)
    equals = top_class == labels.view(*top_class.shape)
    return torch.mean(equals.type(torch.FloatTensor))

### 冻结训练

In [5]:
model = get_deepLavV3(4)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
schedular = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.1, patience=3)

epochs = 25
val_loss_min = np.Inf
max_e = 10

# 模型存放路径
model_path = os.path.join('./model')
name = "InceptionV3_pre"
model = model.to(DEVICE)
for epoch in range(epochs):

    train_loss = 0.0
    val_loss = 0.0
    train_acc = 0.0
    val_acc = 0.0

    model.train()
    for images,labels in tqdm(train_loader):
        optimizer.zero_grad()
        images = images.to(DEVICE)
        labels = labels.to(DEVICE)
        preds,_ = model(images)
        loss = criterion(preds, labels)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        train_acc += accuracy(preds, labels)

    avg_train_loss = train_loss / len(train_loader)
    avg_train_acc = train_acc / len(train_loader)

    model.eval()
    with torch.no_grad():
        for images,labels in tqdm(val_loader):
            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            preds = model(images)
            loss = criterion(preds, labels)
            val_loss += loss.item()
            val_acc += accuracy(preds, labels)

        avg_val_loss = val_loss / len(val_loader)
        avg_val_acc = val_acc / len(val_loader)

    schedular.step(avg_val_loss)

    print("Epoch : {} \ntrain_loss : {:.6f}, \tTrain_acc : {:.6f}, \nVal_loss : {:.6f}, \tVal_acc : {:.6f}".format(epoch + 1,
                                                                                                                   avg_train_loss, avg_train_acc,
                                                                                                                   avg_val_loss, avg_val_acc))
    if avg_val_loss <= val_loss_min:
        print('Validation loss decreased from ({:.6f} --> {:.6f}).\nSaving model ...'.format(val_loss_min, avg_val_loss))
        torch.save(model,os.path.join(model_path,f"{name}.pth"))
        val_loss_min = avg_val_loss
        max_e = 20
    max_e -= 1
    if max_e<=0:
        break


100%|██████████| 244/244 [00:24<00:00,  9.87it/s]


Epoch : 1 
train_loss : 0.892395, 	Train_acc : 0.631608, 
Val_loss : 0.638627, 	Val_acc : 0.755328
Validation loss decreased from (inf --> 0.638627).
Saving model ...


100%|██████████| 244/244 [00:24<00:00,  9.88it/s]


Epoch : 2 
train_loss : 0.771784, 	Train_acc : 0.690380, 
Val_loss : 0.615903, 	Val_acc : 0.778962
Validation loss decreased from (0.638627 --> 0.615903).
Saving model ...


100%|██████████| 244/244 [00:25<00:00,  9.49it/s]


Epoch : 3 
train_loss : 0.751810, 	Train_acc : 0.698488, 
Val_loss : 0.621691, 	Val_acc : 0.768853


100%|██████████| 244/244 [00:24<00:00,  9.93it/s]


Epoch : 4 
train_loss : 0.745506, 	Train_acc : 0.701930, 
Val_loss : 0.597029, 	Val_acc : 0.763525
Validation loss decreased from (0.615903 --> 0.597029).
Saving model ...


100%|██████████| 244/244 [00:24<00:00,  9.99it/s]


Epoch : 5 
train_loss : 0.729769, 	Train_acc : 0.710654, 
Val_loss : 0.659505, 	Val_acc : 0.763524


100%|██████████| 244/244 [00:24<00:00, 10.00it/s]


Epoch : 6 
train_loss : 0.725808, 	Train_acc : 0.716256, 
Val_loss : 0.571568, 	Val_acc : 0.782924
Validation loss decreased from (0.597029 --> 0.571568).
Saving model ...


100%|██████████| 244/244 [00:26<00:00,  9.15it/s]


Epoch : 7 
train_loss : 0.710236, 	Train_acc : 0.723113, 
Val_loss : 0.606835, 	Val_acc : 0.787432


100%|██████████| 244/244 [00:24<00:00,  9.85it/s]


Epoch : 8 
train_loss : 0.713460, 	Train_acc : 0.721769, 
Val_loss : 0.604279, 	Val_acc : 0.790983


100%|██████████| 244/244 [00:24<00:00,  9.99it/s]


Epoch : 9 
train_loss : 0.708958, 	Train_acc : 0.719107, 
Val_loss : 0.645273, 	Val_acc : 0.776776


100%|██████████| 244/244 [00:25<00:00,  9.68it/s]


Epoch : 10 
train_loss : 0.704067, 	Train_acc : 0.721496, 
Val_loss : 0.614827, 	Val_acc : 0.803962


100%|██████████| 244/244 [00:24<00:00,  9.80it/s]


Epoch : 11 
train_loss : 0.666677, 	Train_acc : 0.737396, 
Val_loss : 0.612392, 	Val_acc : 0.803415


100%|██████████| 244/244 [00:24<00:00,  9.83it/s]


Epoch : 12 
train_loss : 0.647097, 	Train_acc : 0.747373, 
Val_loss : 0.616484, 	Val_acc : 0.798497


100%|██████████| 244/244 [00:24<00:00,  9.85it/s]


Epoch : 13 
train_loss : 0.652059, 	Train_acc : 0.742089, 
Val_loss : 0.617157, 	Val_acc : 0.804235


100%|██████████| 244/244 [00:24<00:00,  9.91it/s]


Epoch : 14 
train_loss : 0.644994, 	Train_acc : 0.745348, 
Val_loss : 0.633357, 	Val_acc : 0.795492


100%|██████████| 244/244 [00:25<00:00,  9.61it/s]


Epoch : 15 
train_loss : 0.636095, 	Train_acc : 0.750242, 
Val_loss : 0.628259, 	Val_acc : 0.801776


100%|██████████| 244/244 [00:24<00:00,  9.92it/s]


Epoch : 16 
train_loss : 0.638637, 	Train_acc : 0.748992, 
Val_loss : 0.626239, 	Val_acc : 0.798087


100%|██████████| 244/244 [00:24<00:00, 10.13it/s]


Epoch : 17 
train_loss : 0.644238, 	Train_acc : 0.746758, 
Val_loss : 0.625094, 	Val_acc : 0.803415


100%|██████████| 244/244 [00:24<00:00,  9.86it/s]


Epoch : 18 
train_loss : 0.649456, 	Train_acc : 0.742885, 
Val_loss : 0.629901, 	Val_acc : 0.787432


100%|██████████| 244/244 [00:24<00:00,  9.97it/s]


Epoch : 19 
train_loss : 0.640824, 	Train_acc : 0.748060, 
Val_loss : 0.626428, 	Val_acc : 0.793579


100%|██████████| 244/244 [00:24<00:00,  9.83it/s]


Epoch : 20 
train_loss : 0.644542, 	Train_acc : 0.744666, 
Val_loss : 0.626106, 	Val_acc : 0.800137


100%|██████████| 244/244 [00:24<00:00, 10.11it/s]


Epoch : 21 
train_loss : 0.637732, 	Train_acc : 0.749128, 
Val_loss : 0.625320, 	Val_acc : 0.794399


100%|██████████| 244/244 [00:25<00:00,  9.67it/s]


Epoch : 22 
train_loss : 0.641133, 	Train_acc : 0.746668, 
Val_loss : 0.623771, 	Val_acc : 0.792350


100%|██████████| 244/244 [00:23<00:00, 10.24it/s]


Epoch : 23 
train_loss : 0.638755, 	Train_acc : 0.747304, 
Val_loss : 0.620605, 	Val_acc : 0.797268


100%|██████████| 244/244 [00:24<00:00,  9.96it/s]


Epoch : 24 
train_loss : 0.644522, 	Train_acc : 0.745776, 
Val_loss : 0.627244, 	Val_acc : 0.799727


100%|██████████| 244/244 [00:24<00:00, 10.04it/s]

Epoch : 25 
train_loss : 0.636012, 	Train_acc : 0.748581, 
Val_loss : 0.628385, 	Val_acc : 0.798087


In [6]:
val_loss_min

0.5715676234027401

### 解冻参数

In [7]:
model = torch.load(os.path.join(model_path,f"{name}.pth"))

for param in model.Mixed_7c.parameters():
    param.requires_grad = True
for param in model.Mixed_7b.parameters():
    param.requires_grad = True
for param in model.Mixed_7a.parameters():
    param.requires_grad = True

# for k,v in model.named_parameters():
#     print(f"{k}: {v.requires_grad}")
# model

### finetune

In [8]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
schedular = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.1, patience=3)

epochs =25
# val_loss_min = np.Inf
max_e = 10

name = "InceptionV3_pre_finetune"
model = model.to(DEVICE)
for epoch in range(epochs):

    train_loss = 0.0
    val_loss = 0.0
    train_acc = 0.0
    val_acc = 0.0

    model.train()
    for images,labels in tqdm(train_loader):
        optimizer.zero_grad()
        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        preds,_ = model(images)
        loss = criterion(preds, labels)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        train_acc += accuracy(preds, labels)

    avg_train_loss = train_loss / len(train_loader)
    avg_train_acc = train_acc / len(train_loader)

    model.eval()
    with torch.no_grad():
        for images,labels in tqdm(val_loader):
            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            preds = model(images)
            loss = criterion(preds, labels)
            val_loss += loss.item()
            val_acc += accuracy(preds, labels)

        avg_val_loss = val_loss / len(val_loader)
        avg_val_acc = val_acc / len(val_loader)

    schedular.step(avg_val_loss)

    print("Epoch : {} \ntrain_loss : {:.6f}, \tTrain_acc : {:.6f}, \nVal_loss : {:.6f}, \tVal_acc : {:.6f}".format(epoch + 1,
                                                                                                                   avg_train_loss, avg_train_acc,
                                                                                                                   avg_val_loss, avg_val_acc))
    if avg_val_loss <= val_loss_min:
        print('Validation loss decreased from ({:.6f} --> {:.6f}).\nSaving model ...'.format(val_loss_min, avg_val_loss))
        torch.save(model, os.path.join(model_path,f"{name}.pth"))
        val_loss_min = avg_val_loss
        max_e = 10
    max_e -= 1
    if max_e<=0:
        break


100%|██████████| 244/244 [00:24<00:00, 10.01it/s]


Epoch : 1 
train_loss : 0.510907, 	Train_acc : 0.806536, 
Val_loss : 0.372776, 	Val_acc : 0.869672
Validation loss decreased from (0.571568 --> 0.372776).
Saving model ...


100%|██████████| 244/244 [00:24<00:00,  9.77it/s]


Epoch : 2 
train_loss : 0.386504, 	Train_acc : 0.854302, 
Val_loss : 0.359843, 	Val_acc : 0.872131
Validation loss decreased from (0.372776 --> 0.359843).
Saving model ...


100%|██████████| 244/244 [00:23<00:00, 10.37it/s]


Epoch : 3 
train_loss : 0.334233, 	Train_acc : 0.873983, 
Val_loss : 0.312147, 	Val_acc : 0.899590
Validation loss decreased from (0.359843 --> 0.312147).
Saving model ...


100%|██████████| 244/244 [00:25<00:00,  9.63it/s]


Epoch : 4 
train_loss : 0.304362, 	Train_acc : 0.883734, 
Val_loss : 0.298153, 	Val_acc : 0.903825
Validation loss decreased from (0.312147 --> 0.298153).
Saving model ...


100%|██████████| 244/244 [00:25<00:00,  9.74it/s]


Epoch : 5 
train_loss : 0.279127, 	Train_acc : 0.893393, 
Val_loss : 0.302812, 	Val_acc : 0.900409


100%|██████████| 244/244 [00:24<00:00,  9.85it/s]


Epoch : 6 
train_loss : 0.260283, 	Train_acc : 0.903664, 
Val_loss : 0.279971, 	Val_acc : 0.902459
Validation loss decreased from (0.298153 --> 0.279971).
Saving model ...


100%|██████████| 244/244 [00:24<00:00,  9.99it/s]


Epoch : 7 
train_loss : 0.243322, 	Train_acc : 0.910614, 
Val_loss : 0.285521, 	Val_acc : 0.892213


100%|██████████| 244/244 [00:24<00:00,  9.93it/s]


Epoch : 8 
train_loss : 0.235160, 	Train_acc : 0.912276, 
Val_loss : 0.261607, 	Val_acc : 0.912431
Validation loss decreased from (0.279971 --> 0.261607).
Saving model ...


100%|██████████| 244/244 [00:25<00:00,  9.66it/s]


Epoch : 9 
train_loss : 0.217291, 	Train_acc : 0.921320, 
Val_loss : 0.275865, 	Val_acc : 0.903824


100%|██████████| 244/244 [00:22<00:00, 10.81it/s]


Epoch : 10 
train_loss : 0.214269, 	Train_acc : 0.922687, 
Val_loss : 0.264187, 	Val_acc : 0.902049


100%|██████████| 244/244 [00:23<00:00, 10.22it/s]


Epoch : 11 
train_loss : 0.200284, 	Train_acc : 0.926855, 
Val_loss : 0.268917, 	Val_acc : 0.903688


100%|██████████| 244/244 [00:24<00:00,  9.91it/s]


Epoch : 12 
train_loss : 0.189437, 	Train_acc : 0.930203, 
Val_loss : 0.261944, 	Val_acc : 0.902049


100%|██████████| 244/244 [00:24<00:00,  9.94it/s]


Epoch : 13 
train_loss : 0.155373, 	Train_acc : 0.943210, 
Val_loss : 0.222164, 	Val_acc : 0.916803
Validation loss decreased from (0.261607 --> 0.222164).
Saving model ...


100%|██████████| 244/244 [00:24<00:00,  9.91it/s]


Epoch : 14 
train_loss : 0.143409, 	Train_acc : 0.948998, 
Val_loss : 0.227652, 	Val_acc : 0.917213


100%|██████████| 244/244 [00:22<00:00, 10.91it/s]


Epoch : 15 
train_loss : 0.134754, 	Train_acc : 0.951754, 
Val_loss : 0.207232, 	Val_acc : 0.923360
Validation loss decreased from (0.222164 --> 0.207232).
Saving model ...


100%|██████████| 244/244 [00:25<00:00,  9.65it/s]


Epoch : 16 
train_loss : 0.129776, 	Train_acc : 0.952593, 
Val_loss : 0.212084, 	Val_acc : 0.921311


100%|██████████| 244/244 [00:24<00:00,  9.88it/s]


Epoch : 17 
train_loss : 0.126873, 	Train_acc : 0.953736, 
Val_loss : 0.220106, 	Val_acc : 0.915574


100%|██████████| 244/244 [00:25<00:00,  9.75it/s]


Epoch : 18 
train_loss : 0.123282, 	Train_acc : 0.955810, 
Val_loss : 0.206184, 	Val_acc : 0.924180
Validation loss decreased from (0.207232 --> 0.206184).
Saving model ...


100%|██████████| 244/244 [00:22<00:00, 10.68it/s]


Epoch : 19 
train_loss : 0.118195, 	Train_acc : 0.956880, 
Val_loss : 0.218737, 	Val_acc : 0.915573


100%|██████████| 244/244 [00:25<00:00,  9.72it/s]


Epoch : 20 
train_loss : 0.112436, 	Train_acc : 0.958429, 
Val_loss : 0.216738, 	Val_acc : 0.918442


100%|██████████| 244/244 [00:24<00:00, 10.05it/s]


Epoch : 21 
train_loss : 0.107837, 	Train_acc : 0.962301, 
Val_loss : 0.207267, 	Val_acc : 0.912705


100%|██████████| 244/244 [00:24<00:00,  9.86it/s]


Epoch : 22 
train_loss : 0.109104, 	Train_acc : 0.961047, 
Val_loss : 0.204716, 	Val_acc : 0.922131
Validation loss decreased from (0.206184 --> 0.204716).
Saving model ...


100%|██████████| 244/244 [00:24<00:00,  9.79it/s]


Epoch : 23 
train_loss : 0.103188, 	Train_acc : 0.961800, 
Val_loss : 0.199904, 	Val_acc : 0.924590
Validation loss decreased from (0.204716 --> 0.199904).
Saving model ...


100%|██████████| 244/244 [00:25<00:00,  9.70it/s]


Epoch : 24 
train_loss : 0.101842, 	Train_acc : 0.964146, 
Val_loss : 0.188753, 	Val_acc : 0.925819
Validation loss decreased from (0.199904 --> 0.188753).
Saving model ...


100%|██████████| 244/244 [00:24<00:00, 10.17it/s]

Epoch : 25 
train_loss : 0.101155, 	Train_acc : 0.963327, 
Val_loss : 0.199174, 	Val_acc : 0.922131


In [9]:
val_loss_min

0.18875324098607066

### 测试

In [7]:
name = "InceptionV3_pre_finetune"
model_path = os.path.join('./model')
model = torch.load(os.path.join(model_path,f"{name}.pth"))
model = model.to(DEVICE)
criterion = nn.CrossEntropyLoss()

# 混淆矩阵
M = np.zeros((4,4))
with torch.no_grad():
    test_loss=0
    test_acc=0
    for images,labels in tqdm(test_loader):
        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        preds = model(images)
        loss = criterion(preds, labels)
        test_loss += loss.item()
        test_acc += accuracy(preds, labels)
        
        M[preds.argmax(),labels[0]]+=1
        
    avg_test_loss = test_loss / len(test_loader)
    avg_test_acc = test_acc / len(test_loader)
    print("Test_loss : {:.6f}, \tTest_acc : {:.6f}".format(avg_test_loss,avg_test_acc))
    
    M = M.astype("int")
    print(M)
    

100%|██████████| 2706/2706 [01:07<00:00, 39.91it/s]

Test_loss : 0.198834, 	Test_acc : 0.929047
[[ 360    3    3    0]
 [   4  764   33   22]
 [   3   65 1132    4]
 [   0   47    8  258]]
